feat : implement new application registry analytics category - EXO-61480 -Meeds-io/MIPs#37
Meeds-io/analytics pull request #111
Opened 2023-01-02 10:40 UTC by sofyenne

2023-01-05 15:41 UTC, azayati requested changes

2023-01-05 15:41 UTC, azayati commented on analytics-webapps/src/main/webapp/WEB-INF/conf/analytics/application-registry-configuration.xml
> +    <external-component-plugins>
indentation

2023-01-05 17:12 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-01-05 17:19 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-01-05 18:13 UTC, sofyenne commented on analytics-webapps/src/main/webapp/WEB-INF/conf/analytics/application-registry-configuration.xml
> +    <external-component-plugins>
done !

2023-01-06 09:42 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-01-06 09:51 UTC, azayati approved these changes
LGTM

2023-01-06 09:51 UTC, merged